#!/bin/bash

set -e
cd "$(dirname "$0")/highlightjs"

function clean {
    rm -rf test/detect/objectivescript
    rm -f src/languages/objectivescript.js
    rm -f build/highlight.pack.js
}

trap clean EXIT
clean

cp ../objectivescript.js src/languages/objectivescript.js
mkdir test/detect/objectivescript
touch test/detect/objectivescript/default.txt

npm install
node tools/build.js objectivescript

mv build/highlight.pack.js ../highlight.min.js
